---
name: Deploy to Github Pages

on: push

# sets permissions of the GITHUB_TOKEN to allow deployment ot GitHub pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: provide node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Build frontend
        id: build
        run: |
          npm install
          npm run build
        shell: bash
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # make sure that the current branch is allowed to deploy to this environment.
    # Settings > Environments > github-pages > Deployment branches
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
